name: iOS Core SDK Higgs Sample App Pull Request

on: [pull_request]

defaults:
      run:
        working-directory: core-sdk-samples/higgs-shop-sample-app

jobs:
  swiftlint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run swiftlint
        run: swiftlint

  ui-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run UI tests
        run: xcodebuild test -project HiggsShopSampleApp.xcodeproj -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" -scheme HiggsShopSampleApp

  run-tests-with-thread-sanitizer:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests with thread sanitizer
        run: xcodebuild test -project HiggsShopSampleApp.xcodeproj -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" -scheme HiggsShopSampleApp -enableThreadSanitizer YES


  run-tests-with-address-sanitizer:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests with address sanitizer
        run: xcodebuild test -project HiggsShopSampleApp.xcodeproj -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" -scheme HiggsShopSampleApp -enableAddressSanitizer YES

  run-analyzer:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run static analyzer
        run: xcodebuild analyze -project HiggsShopSampleApp.xcodeproj -scheme HiggsShopSampleApp -destination "platform=iOS Simulator,name=iPhone 12,OS=latest"
